using ExpressionToSQL.common.configuration;
using System;

namespace ExpressionToSQL
{
    public class SqlConfiguration : ICommandConfiguration, IQueryConfiguration
    {
        public bool? AutoGeneratedId { get; set; } = true;

        public bool? FieldsInclude { get; set; } = false;

        public bool? PropsInclude { get; set; } = true;

        public bool? WihNoLock { get; set; } = true;

        public string KeyTableDefault { get; set; } = "Id";

        public string OrderBy { get; set; } = "Id";

        public bool? IncludeId { get; set; } = false;

        public string TableName { get; set; } = null;
    }
}
